### ISSUE TITLE
内核崩溃

### ISSUE THREAD

**Issue by eternalstop** [zzgang/kconnp#6]
![qq 20160420182420](https://cloud.githubusercontent.com/assets/17778173/14671503/ab9f54d4-0724-11e6-836d-6f112363c93f.png)
运行kconnp start 之后就内核崩溃了

**Comment by zzgang** [comment]
感谢反馈，你查看一下 安装版本 kconnp -v,包括 /etc/primitives.deny的内容，给出来。

**Comment by eternalstop** [comment]
![qq 20160426091240](https://cloud.githubusercontent.com/assets/17778173/14803700/95b77a20-0b8e-11e6-838a-c4fc3177b1dc.png)
版本就是最新的这个，我装上去还没改呢。

**Comment by zzgang** [comment]
稍等，我在你的这个本本的内核下测试一下。

**Comment by zzgang** [comment]
在版本2.6.32-431.23.3.el6.x86_64下默认安装后，没有发现问题，确定是刚安装完成后，没有任何改动就发上错误了吗？

**Comment by zzgang** [comment]
方便加我个QQ吧，线上聊，737781325

**Comment by zzgang** [comment]
已发布新版，已修正。
